on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/application
          file: ./services/application/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/sporollan-application:latest
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/sporollan-application:${{ github.sha }}
