on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Test FastAPI App (PR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/application/requirements.txt

      - name: Run pytest
        working-directory: services/application
        run: |
          pytest --maxfail=1 --disable-warnings -q
