on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Test FastAPI App (PR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Smoke test JSON endpoint
        run: |
          python - <<EOF
          import requests
          resp = requests.get('http://localhost:8000/greeting')
          # Ensure the response is JSON
          assert resp.headers.get('Content-Type') == 'application/json', f"Expected JSON response, got {resp.headers.get('Content-Type')}"
          # Parse JSON and verify greeting
          data = resp.json()
          assert 'greeting' in data, "Response JSON should contain 'greeting'"
          assert isinstance(data['greeting'], str) and data['greeting'], "Greeting should be a non-empty string"
          print('Smoke test passed')
          EOF

