name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'k8s/**'

jobs:
  apply:
    name: Apply Terraform and deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:   ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest' 

      - name: Update EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-app
          kubectl apply -k ./k8s/overlays/prod

